apiVersion: v1
kind: Service
metadata:
  name: heart-api-svc
  namespace: prod
  labels:
    app: heart-api
spec:
  selector:
    app: heart-api
    slot: blue        # start with blue; patch to green on cutover
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: LoadBalancer
